### ISSUE TITLE
Integrate with payment systems (paypal, PagSeguro, etc)

### ISSUE THREAD

**Issue by juliarizza** [juliarizza/web2courses#3]

**Comment by juliarizza** [comment]
PayPal integration DONE.

**Comment by rodgomesc** [comment]
congratulations!

**Comment by juliarizza** [comment]
PagSeguro will not be implemented. Worst documentation ever. Not a secure method. Just don't.

**Comment by juliarizza** [comment]
For now, this task is closed. In the need of any other payment system, it'll be continued.
